/*
 * AUTOGENERATED by mrustc
 */
#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>
#include <stdarg.h>
#include <assert.h>
#include <stdatomic.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <setjmp.h>
typedef uint32_t RUST_CHAR;
typedef uint8_t RUST_BOOL;
typedef struct { void* PTR; size_t META; } SLICE_PTR;
typedef struct { void* PTR; void* META; } TRAITOBJ_PTR;
typedef struct { void (*drop)(void*); size_t size; size_t align; } VTABLE_HDR;
typedef struct { char _d; } tUNIT;
typedef char tBANG;
typedef struct { char _d; } tTYPEID;
static inline size_t ALIGN_TO(size_t s, size_t a) { return (s + a-1) / a * a; }

extern void _Unwind_Resume(void) __attribute__((noreturn));
#define ALIGNOF(t) __alignof__(t)
extern __thread jmp_buf*    mrustc_panic_target;
extern __thread void* mrustc_panic_value;
static inline uint64_t __builtin_clz64(uint64_t v) {
	return ( (v >> 32) != 0 ? __builtin_clz(v>>32) : 32 + __builtin_clz(v));
}
static inline uint64_t __builtin_ctz64(uint64_t v) {
	return ((v&0xFFFFFFFF) == 0 ? __builtin_ctz(v>>32) + 32 : __builtin_ctz(v));
}
static inline uint8_t __mrustc_atomicloop8(volatile uint8_t* slot, uint8_t param, int ordering, uint8_t (*cb)(uint8_t, uint8_t)) { int ordering_load = (ordering == memory_order_release || ordering == memory_order_acq_rel ? memory_order_relaxed : ordering); for(;;) { uint8_t v = atomic_load_explicit((_Atomic uint8_t*)slot, ordering_load); if( atomic_compare_exchange_strong_explicit((_Atomic uint8_t*)slot, &v, cb(v, param), ordering, ordering_load) ) return v; }}
static inline uint16_t __mrustc_atomicloop16(volatile uint16_t* slot, uint16_t param, int ordering, uint16_t (*cb)(uint16_t, uint16_t)) { int ordering_load = (ordering == memory_order_release || ordering == memory_order_acq_rel ? memory_order_relaxed : ordering); for(;;) { uint16_t v = atomic_load_explicit((_Atomic uint16_t*)slot, ordering_load); if( atomic_compare_exchange_strong_explicit((_Atomic uint16_t*)slot, &v, cb(v, param), ordering, ordering_load) ) return v; }}
static inline uint32_t __mrustc_atomicloop32(volatile uint32_t* slot, uint32_t param, int ordering, uint32_t (*cb)(uint32_t, uint32_t)) { int ordering_load = (ordering == memory_order_release || ordering == memory_order_acq_rel ? memory_order_relaxed : ordering); for(;;) { uint32_t v = atomic_load_explicit((_Atomic uint32_t*)slot, ordering_load); if( atomic_compare_exchange_strong_explicit((_Atomic uint32_t*)slot, &v, cb(v, param), ordering, ordering_load) ) return v; }}
static inline uint64_t __mrustc_atomicloop64(volatile uint64_t* slot, uint64_t param, int ordering, uint64_t (*cb)(uint64_t, uint64_t)) { int ordering_load = (ordering == memory_order_release || ordering == memory_order_acq_rel ? memory_order_relaxed : ordering); for(;;) { uint64_t v = atomic_load_explicit((_Atomic uint64_t*)slot, ordering_load); if( atomic_compare_exchange_strong_explicit((_Atomic uint64_t*)slot, &v, cb(v, param), ordering, ordering_load) ) return v; }}
typedef unsigned __int128 uint128_t;
typedef signed __int128 int128_t;
static inline uint128_t __builtin_bswap128(uint128_t v) {
	uint64_t lo = __builtin_bswap64((uint64_t)v);
	uint64_t hi = __builtin_bswap64((uint64_t)(v>>64));
	return ((uint128_t)lo << 64) | (uint128_t)hi;
}
static inline uint128_t intrinsic_ctlz_u128(uint128_t v) {
	return (v == 0 ? 128 : (v >> 64 != 0 ? __builtin_clz64(v>>64) : 64 + __builtin_clz64(v)));
}
static inline uint128_t intrinsic_cttz_u128(uint128_t v) {
	return (v == 0 ? 128 : ((v&0xFFFFFFFFFFFFFFFF) == 0 ? __builtin_ctz64(v>>64) + 64 : __builtin_ctz64(v)));
}

static inline int slice_cmp(SLICE_PTR l, SLICE_PTR r) {
	int rv = memcmp(l.PTR, r.PTR, l.META < r.META ? l.META : r.META);
	if(rv != 0) return rv;
	if(l.META < r.META) return -1;
	if(l.META > r.META) return 1;
	return 0;
}
static inline SLICE_PTR make_sliceptr(void* ptr, size_t s) { SLICE_PTR rv = { ptr, s }; return rv; }
static inline TRAITOBJ_PTR make_traitobjptr(void* ptr, void* vt) { TRAITOBJ_PTR rv = { ptr, vt }; return rv; }

static inline size_t mrustc_max(size_t a, size_t b) { return a < b ? b : a; }
static inline void noop_drop(tUNIT *p) { }

static inline size_t mrustc_string_search_linear(SLICE_PTR val, size_t count, SLICE_PTR* options) {
	for(size_t i = 0; i < count; i ++) {
		int cmp = slice_cmp(val, options[i]);
		if(cmp < 0) break;
		if(cmp == 0) return i;
	}
	return SIZE_MAX;
}
static const uint8_t __mrustc_revmap[16] = { 0, 8, 4,12, 2,10, 6,14,  1, 9, 5,13, 3, 7,15};
static inline uint8_t __mrustc_bitrev8(uint8_t v) { if(v==0||v==0xFF) return v; return __mrustc_revmap[v>>4]|(__mrustc_revmap[v&15]<<4); }
static inline uint16_t __mrustc_bitrev16(uint16_t v) { if(v==0) return 0; return ((uint16_t)__mrustc_bitrev8(v>>8))|((uint16_t)__mrustc_bitrev8(v)<<8); }
static inline uint32_t __mrustc_bitrev32(uint32_t v) { if(v==0) return 0; return ((uint32_t)__mrustc_bitrev16(v>>16))|((uint32_t)__mrustc_bitrev16(v)<<16); }
static inline uint64_t __mrustc_bitrev64(uint64_t v) { if(v==0) return 0; return ((uint64_t)__mrustc_bitrev32(v>>32))|((uint64_t)__mrustc_bitrev32(v)<<32); }
static inline uint128_t __mrustc_bitrev128(uint128_t v) { if(v==0) return 0; uint128_t rv = ((uint128_t)__mrustc_bitrev64(v>>64))|((uint128_t)__mrustc_bitrev64(v)<<64); return rv; }
static inline uint8_t __mrustc_op_umax8(uint8_t a, uint8_t b) { return (a > b ? a : b); }
static inline uint8_t __mrustc_op_umin8(uint8_t a, uint8_t b) { return (a < b ? a : b); }
static inline uint8_t __mrustc_op_imax8(uint8_t a, uint8_t b) { return ((int8_t)a > (int8_t)b ? a : b); }
static inline uint8_t __mrustc_op_imin8(uint8_t a, uint8_t b) { return ((int8_t)a < (int8_t)b ? a : b); }
static inline uint8_t __mrustc_op_and_not8(uint8_t a, uint8_t b) { return ~(a & b); }
static inline uint16_t __mrustc_op_umax16(uint16_t a, uint16_t b) { return (a > b ? a : b); }
static inline uint16_t __mrustc_op_umin16(uint16_t a, uint16_t b) { return (a < b ? a : b); }
static inline uint16_t __mrustc_op_imax16(uint16_t a, uint16_t b) { return ((int16_t)a > (int16_t)b ? a : b); }
static inline uint16_t __mrustc_op_imin16(uint16_t a, uint16_t b) { return ((int16_t)a < (int16_t)b ? a : b); }
static inline uint16_t __mrustc_op_and_not16(uint16_t a, uint16_t b) { return ~(a & b); }
static inline uint32_t __mrustc_op_umax32(uint32_t a, uint32_t b) { return (a > b ? a : b); }
static inline uint32_t __mrustc_op_umin32(uint32_t a, uint32_t b) { return (a < b ? a : b); }
static inline uint32_t __mrustc_op_imax32(uint32_t a, uint32_t b) { return ((int32_t)a > (int32_t)b ? a : b); }
static inline uint32_t __mrustc_op_imin32(uint32_t a, uint32_t b) { return ((int32_t)a < (int32_t)b ? a : b); }
static inline uint32_t __mrustc_op_and_not32(uint32_t a, uint32_t b) { return ~(a & b); }
static inline uint64_t __mrustc_op_umax64(uint64_t a, uint64_t b) { return (a > b ? a : b); }
static inline uint64_t __mrustc_op_umin64(uint64_t a, uint64_t b) { return (a < b ? a : b); }
static inline uint64_t __mrustc_op_imax64(uint64_t a, uint64_t b) { return ((int64_t)a > (int64_t)b ? a : b); }
static inline uint64_t __mrustc_op_imin64(uint64_t a, uint64_t b) { return ((int64_t)a < (int64_t)b ? a : b); }
static inline uint64_t __mrustc_op_and_not64(uint64_t a, uint64_t b) { return ~(a & b); }
// struct ::"core-0_0_0"::option::Option#Some<&'static [::"core-0_0_0"::fmt::rt::v1::Argument/*S*/],>
struct s_ZRG2cE9core0_0_06optionG10OptionSome1gBsSG4c_A3fmt2rt2v18Argument0g  {
	/*@0*/SLICE_PTR _0; // &'static [::"core-0_0_0"::fmt::rt::v1::Argument/*S*/]
} ;
typedef char sizeof_assert_ZRG2cE9core0_0_06optionG10OptionSome1gBsSG4c_A3fmt2rt2v18Argument0g[ (sizeof(struct s_ZRG2cE9core0_0_06optionG10OptionSome1gBsSG4c_A3fmt2rt2v18Argument0g) == 16) ? 1 : -1 ];
typedef char alignof_assert_ZRG2cE9core0_0_06optionG10OptionSome1gBsSG4c_A3fmt2rt2v18Argument0g[ (ALIGNOF(struct s_ZRG2cE9core0_0_06optionG10OptionSome1gBsSG4c_A3fmt2rt2v18Argument0g) == 8) ? 1 : -1 ];
// enum ::"core-0_0_0"::option::Option<&'static [::"core-0_0_0"::fmt::rt::v1::Argument/*S*/],>
struct e_ZRG2cE9core0_0_06option6Option1gBsSG4c_A3fmt2rt2v18Argument0g {
	struct {
		struct s_ZRG2cE9core0_0_06optionG10OptionSome1gBsSG4c_A3fmt2rt2v18Argument0g var_1;
	} DATA;
};
typedef char sizeof_assert_ZRG2cE9core0_0_06option6Option1gBsSG4c_A3fmt2rt2v18Argument0g[ (sizeof(struct e_ZRG2cE9core0_0_06option6Option1gBsSG4c_A3fmt2rt2v18Argument0g) == 16) ? 1 : -1 ];
// struct ::"core-0_0_0"::fmt::Arguments<'static,>
struct s_ZRG2cE9core0_0_03fmt9Arguments0g  {
	/*@0*/SLICE_PTR _0; // &'static [&'static str]
	/*@16*/struct e_ZRG2cE9core0_0_06option6Option1gBsSG4c_A3fmt2rt2v18Argument0g _1; // ::"core-0_0_0"::option::Option<&'static [::"core-0_0_0"::fmt::rt::v1::Argument/*S*/],>/*E*/
	/*@32*/SLICE_PTR _2; // &'static [::"core-0_0_0"::fmt::ArgumentV1<'static,>/*S*/]
} ;
typedef char sizeof_assert_ZRG2cE9core0_0_03fmt9Arguments0g[ (sizeof(struct s_ZRG2cE9core0_0_03fmt9Arguments0g) == 48) ? 1 : -1 ];
typedef char alignof_assert_ZRG2cE9core0_0_03fmt9Arguments0g[ (ALIGNOF(struct s_ZRG2cE9core0_0_03fmt9Arguments0g) == 8) ? 1 : -1 ];
typedef void (*t_ZRTF0T0 )(void); // extern "Rust" fn() -> ()
// struct ::"std-0_0_0"::rt::closure#lang_start_0<(),>
struct s_ZRG2cD8std0_0_02rtH19closurelang_start_01gT0  {
	/*@0*/t_ZRTF0T0 _0; // extern "Rust" fn() -> ()
} ;
typedef char sizeof_assert_ZRG2cD8std0_0_02rtH19closurelang_start_01gT0[ (sizeof(struct s_ZRG2cD8std0_0_02rtH19closurelang_start_01gT0) == 8) ? 1 : -1 ];
typedef char alignof_assert_ZRG2cD8std0_0_02rtH19closurelang_start_01gT0[ (ALIGNOF(struct s_ZRG2cD8std0_0_02rtH19closurelang_start_01gT0) == 8) ? 1 : -1 ];
typedef struct t_ZRTA1BsCy  { SLICE_PTR  DATA[1]; } t_ZRTA1BsCy ; // [&'static str; 1]
struct s_ZRG2cE9core0_0_03fmt4Void0g;
struct e_ZRG2cE9core0_0_06result6Result2gT0G2c_A3fmt5Error0g;
struct s_ZRG2cE9core0_0_03fmt9Formatter0g;
typedef struct e_ZRG2cE9core0_0_06result6Result2gT0G2c_A3fmt5Error0g  (*t_ZRTF2BsG2cE9core0_0_03fmt4Void0gBuG2c_A_B9Formatter0gG2c_A6result6Result2gT0G2c_A_B5Error0g )( struct s_ZRG2cE9core0_0_03fmt4Void0g *, struct s_ZRG2cE9core0_0_03fmt9Formatter0g * ); // for<'elided#0,'elided#1,> extern "Rust" fn(&'H0 ::"core-0_0_0"::fmt::Void/*S*/, &'H1 mut ::"core-0_0_0"::fmt::Formatter<'H1,>/*S*/, ) -> ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::fmt::Error/*S*/,>/*E*/
// struct ::"core-0_0_0"::fmt::ArgumentV1<'static,>
struct s_ZRG2cE9core0_0_03fmt10ArgumentV10g  {
	/*@0*/struct s_ZRG2cE9core0_0_03fmt4Void0g *_0; // &'static ::"core-0_0_0"::fmt::Void/*S*/
	/*@8*/t_ZRTF2BsG2cE9core0_0_03fmt4Void0gBuG2c_A_B9Formatter0gG2c_A6result6Result2gT0G2c_A_B5Error0g _1; // for<'elided#0,'elided#1,> extern "Rust" fn(&'H0 ::"core-0_0_0"::fmt::Void/*S*/, &'H1 mut ::"core-0_0_0"::fmt::Formatter<'H1,>/*S*/, ) -> ::"core-0_0_0"::result::Result<(),::"core-0_0_0"::fmt::Error/*S*/,>/*E*/
} ;
typedef char sizeof_assert_ZRG2cE9core0_0_03fmt10ArgumentV10g[ (sizeof(struct s_ZRG2cE9core0_0_03fmt10ArgumentV10g) == 16) ? 1 : -1 ];
typedef char alignof_assert_ZRG2cE9core0_0_03fmt10ArgumentV10g[ (ALIGNOF(struct s_ZRG2cE9core0_0_03fmt10ArgumentV10g) == 8) ? 1 : -1 ];
typedef struct t_ZRTA0G2cE9core0_0_03fmt10ArgumentV10g  { char _d; }  __attribute__((__aligned__(8),))t_ZRTA0G2cE9core0_0_03fmt10ArgumentV10g ; // [::"core-0_0_0"::fmt::ArgumentV1<'static,>/*S*/; 0]
typedef void (*t_ZRTF1PoT0T0 )( tUNIT * ); // extern "Rust" fn(*move (), ) -> ()
typedef int32_t  (*t_ZRTFeE8rustcall2BsT0T0Cf )( tUNIT *, tUNIT  ); // for<'elided#0,> extern "rust-call" fn(&'H0 (), (), ) -> i32
typedef int32_t  (*t_ZRTFeE8rustcall2BuT0T0Cf )( tUNIT *, tUNIT  ); // for<'elided#0,> extern "rust-call" fn(&'H0 mut (), (), ) -> i32
struct s_ZRG3cE9core0_0_03ops8functionF11FnMutvtable2gT0Cf;
// struct ::"core-0_0_0"::ops::function::Fn#vtable<(),i32,>
struct s_ZRG3cE9core0_0_03ops8functionC8Fnvtable2gT0Cf  {
	/*@0*/t_ZRTF1PoT0T0 _0; // extern "Rust" fn(*move (), ) -> ()
	/*@8*/uintptr_t _1; // usize
	/*@16*/uintptr_t _2; // usize
	/*@24*/t_ZRTFeE8rustcall2BsT0T0Cf _3; // for<'elided#0,> extern "rust-call" fn(&'H0 (), (), ) -> i32
	/*@32*/t_ZRTFeE8rustcall2BuT0T0Cf _4; // for<'elided#0,> extern "rust-call" fn(&'H0 mut (), (), ) -> i32
	/*@40*/struct s_ZRG3cE9core0_0_03ops8functionF11FnMutvtable2gT0Cf *_5; // &'#omitted ::"core-0_0_0"::ops::function::FnMut#vtable<(),i32,>/*S*/
	/*@48*/// ZST; // ()
} ;
typedef char sizeof_assert_ZRG3cE9core0_0_03ops8functionC8Fnvtable2gT0Cf[ (sizeof(struct s_ZRG3cE9core0_0_03ops8functionC8Fnvtable2gT0Cf) == 48) ? 1 : -1 ];
typedef char alignof_assert_ZRG3cE9core0_0_03ops8functionC8Fnvtable2gT0Cf[ (ALIGNOF(struct s_ZRG3cE9core0_0_03ops8functionC8Fnvtable2gT0Cf) == 8) ? 1 : -1 ];
// struct ::"core-0_0_0"::ops::function::FnMut#vtable<(),i32,>
struct s_ZRG3cE9core0_0_03ops8functionF11FnMutvtable2gT0Cf  {
	/*@0*/t_ZRTF1PoT0T0 _0; // extern "Rust" fn(*move (), ) -> ()
	/*@8*/uintptr_t _1; // usize
	/*@16*/uintptr_t _2; // usize
	/*@24*/t_ZRTFeE8rustcall2BuT0T0Cf _3; // for<'elided#0,> extern "rust-call" fn(&'H0 mut (), (), ) -> i32
	/*@32*/// ZST; // ()
} ;
typedef char sizeof_assert_ZRG3cE9core0_0_03ops8functionF11FnMutvtable2gT0Cf[ (sizeof(struct s_ZRG3cE9core0_0_03ops8functionF11FnMutvtable2gT0Cf) == 32) ? 1 : -1 ];
typedef char alignof_assert_ZRG3cE9core0_0_03ops8functionF11FnMutvtable2gT0Cf[ (ALIGNOF(struct s_ZRG3cE9core0_0_03ops8functionF11FnMutvtable2gT0Cf) == 8) ? 1 : -1 ];
// PROTO extern "Rust" ::"bin#"::main
void  ZRG1cD3bin4main0g(void) // -> ()
;
// PROTO extern "Rust" ::"std-0_0_0"::rt::lang_start<(),>
static intptr_t  ZRG2cD8std0_0_02rt10lang_start1gT0(
		t_ZRTF0T0 arg0, // extern "Rust" fn() -> ()
		intptr_t arg1, // isize
		uint8_t **arg2 // *const *const u8
		) // -> isize
;
// PROTO extern "Rust" <::"std-0_0_0"::rt::closure#lang_start_0<(),>/*S*/ /*- */>::#drop_glue
static void  ZRIG2cD8std0_0_02rtH19closurelang_start_01gT0A9drop_glue0g(
		struct s_ZRG2cD8std0_0_02rtH19closurelang_start_01gT0 *arg0 // &'#omitted move ::"std-0_0_0"::rt::closure#lang_start_0<(),>/*S*/
		) // -> ()
;
// PROTO extern "Rust" <::"std-0_0_0"::rt::closure#lang_start_0<(),>/*S*/ as ::"core-0_0_0"::ops::function::Fn<(),>>::call<'#omitted,>
static int32_t  ZRQG2cD8std0_0_02rtH19closurelang_start_01gT03cE9core0_0_03ops8function2Fn1gT04call0g(
		struct s_ZRG2cD8std0_0_02rtH19closurelang_start_01gT0 *arg0, // &'#omitted ::"std-0_0_0"::rt::closure#lang_start_0<(),>/*S*/
		tUNIT arg1 // ()
		) // -> i32
;
// PROTO extern "Rust" <::"std-0_0_0"::rt::closure#lang_start_0<(),>/*S*/ as ::"core-0_0_0"::ops::function::FnMut<(),>>::call_mut<'#omitted,>
static int32_t  ZRQG2cD8std0_0_02rtH19closurelang_start_01gT03cE9core0_0_03ops8function5FnMut1gT08call_mut0g(
		struct s_ZRG2cD8std0_0_02rtH19closurelang_start_01gT0 *arg0, // &'#omitted mut ::"std-0_0_0"::rt::closure#lang_start_0<(),>/*S*/
		tUNIT arg1 // ()
		) // -> i32
;
// EXTERN extern "Rust" ::"std-0_0_0"::io::stdio::_print<'static,>
extern void  ZRG3cD8std0_0_02io5stdio7__print0g(
		struct s_ZRG2cE9core0_0_03fmt9Arguments0g arg0 // ::"core-0_0_0"::fmt::Arguments<'static,>/*S*/
		) // -> ()
;
// EXTERN extern "Rust" ::"std-0_0_0"::rt::lang_start_internal<'#local0,>
extern intptr_t  ZRG2cD8std0_0_02rt19lang_start_internal0g(
		TRAITOBJ_PTR arg0, // &'#local0 dyn (for ::"core-0_0_0"::ops::function::Fn<(),Output{::"core-0_0_0"::ops::function::FnOnce<(),>}=i32,>+::"core-0_0_0"::marker::Sync+::"std-0_0_0"::panic::RefUnwindSafe+'#local0)
		intptr_t arg1, // isize
		uint8_t **arg2 // *const *const u8
		) // -> isize
;
union u_static_ZRG2cD3binB_09FRAGMENTS0g{ t_ZRTA1BsCy val; uintptr_t raw[2]; } ZRG2cD3binB_09FRAGMENTS0g;	// static ::"bin#"::#0::FRAGMENTS : [&'static str; 1]
union u_static_ZRG1cD3binF6const00g{ t_ZRTA0G2cE9core0_0_03fmt10ArgumentV10g val; uintptr_t raw[0]; } ZRG1cD3binF6const00g;	// static ::"bin#"::const#0 : [::"core-0_0_0"::fmt::ArgumentV1<'static,>/*S*/; 0]
__attribute__((weak)) union u_static_ZRQG2cD8std0_0_02rtH19closurelang_start_01gT03cE9core0_0_03ops8function2Fn1gT0G6vtable0g{ struct s_ZRG3cE9core0_0_03ops8functionC8Fnvtable2gT0Cf val; uintptr_t raw[6]; } ZRQG2cD8std0_0_02rtH19closurelang_start_01gT03cE9core0_0_03ops8function2Fn1gT0G6vtable0g;	// static <::"std-0_0_0"::rt::closure#lang_start_0<(),>/*S*/ as ::"core-0_0_0"::ops::function::Fn<(),>>::vtable# : ::"core-0_0_0"::ops::function::Fn#vtable<(),i32,>/*S*/
__attribute__((weak)) union u_static_ZRQG2cD8std0_0_02rtH19closurelang_start_01gT03cE9core0_0_03ops8function5FnMut1gT0G6vtable0g{ struct s_ZRG3cE9core0_0_03ops8functionF11FnMutvtable2gT0Cf val; uintptr_t raw[4]; } ZRQG2cD8std0_0_02rtH19closurelang_start_01gT03cE9core0_0_03ops8function5FnMut1gT0G6vtable0g;	// static <::"std-0_0_0"::rt::closure#lang_start_0<(),>/*S*/ as ::"core-0_0_0"::ops::function::FnMut<(),>>::vtable# : ::"core-0_0_0"::ops::function::FnMut#vtable<(),i32,>/*S*/
union u_static_ZRG2cD3binB_09FRAGMENTS0g ZRG2cD3binB_09FRAGMENTS0g = { .raw = {(uintptr_t)"Hello, world!\n",0xeull} };	// static ::"bin#"::#0::FRAGMENTS : [&'static str; 1] = 0010000000000000 0E00000000000000{@0x0+8 = "Hello, world!\n"}
union u_static_ZRQG2cD8std0_0_02rtH19closurelang_start_01gT03cE9core0_0_03ops8function2Fn1gT0G6vtable0g ZRQG2cD8std0_0_02rtH19closurelang_start_01gT03cE9core0_0_03ops8function2Fn1gT0G6vtable0g = { .raw = {(uintptr_t)&ZRIG2cD8std0_0_02rtH19closurelang_start_01gT0A9drop_glue0g,0x8ull,0x8ull,(uintptr_t)&ZRQG2cD8std0_0_02rtH19closurelang_start_01gT03cE9core0_0_03ops8function2Fn1gT04call0g,(uintptr_t)&ZRQG2cD8std0_0_02rtH19closurelang_start_01gT03cE9core0_0_03ops8function5FnMut1gT08call_mut0g,(uintptr_t)&ZRQG2cD8std0_0_02rtH19closurelang_start_01gT03cE9core0_0_03ops8function5FnMut1gT0G6vtable0g} };	// static <::"std-0_0_0"::rt::closure#lang_start_0<(),>/*S*/ as ::"core-0_0_0"::ops::function::Fn<(),>>::vtable# : ::"core-0_0_0"::ops::function::Fn#vtable<(),i32,>/*S*/ = 0010000000000000 0800000000000000 0800000000000000 0010000000000000 0010000000000000 0010000000000000{@0x0+8 = &<::"std-0_0_0"::rt::closure#lang_start_0<(),>/*S*/ /*- */>::#drop_glue, @0x18+8 = &<::"std-0_0_0"::rt::closure#lang_start_0<(),>/*S*/ as ::"core-0_0_0"::ops::function::Fn<(),>>::call, @0x20+8 = &<::"std-0_0_0"::rt::closure#lang_start_0<(),>/*S*/ as ::"core-0_0_0"::ops::function::FnMut<(),>>::call_mut, @0x28+8 = &<::"std-0_0_0"::rt::closure#lang_start_0<(),>/*S*/ as ::"core-0_0_0"::ops::function::FnMut<(),>>::vtable#}
union u_static_ZRQG2cD8std0_0_02rtH19closurelang_start_01gT03cE9core0_0_03ops8function5FnMut1gT0G6vtable0g ZRQG2cD8std0_0_02rtH19closurelang_start_01gT03cE9core0_0_03ops8function5FnMut1gT0G6vtable0g = { .raw = {(uintptr_t)&ZRIG2cD8std0_0_02rtH19closurelang_start_01gT0A9drop_glue0g,0x8ull,0x8ull,(uintptr_t)&ZRQG2cD8std0_0_02rtH19closurelang_start_01gT03cE9core0_0_03ops8function5FnMut1gT08call_mut0g} };	// static <::"std-0_0_0"::rt::closure#lang_start_0<(),>/*S*/ as ::"core-0_0_0"::ops::function::FnMut<(),>>::vtable# : ::"core-0_0_0"::ops::function::FnMut#vtable<(),i32,>/*S*/ = 0010000000000000 0800000000000000 0800000000000000 0010000000000000{@0x0+8 = &<::"std-0_0_0"::rt::closure#lang_start_0<(),>/*S*/ /*- */>::#drop_glue, @0x18+8 = &<::"std-0_0_0"::rt::closure#lang_start_0<(),>/*S*/ as ::"core-0_0_0"::ops::function::FnMut<(),>>::call_mut}
// ::"bin#"::main
void  ZRG1cD3bin4main0g(void) // -> ()

{
	tUNIT rv;
	struct s_ZRG2cE9core0_0_03fmt9Arguments0g var1;	// ::"core-0_0_0"::fmt::Arguments<'static,>/*S*/
	struct e_ZRG2cE9core0_0_06option6Option1gBsSG4c_A3fmt2rt2v18Argument0g var2;	// ::"core-0_0_0"::option::Option<&'static [::"core-0_0_0"::fmt::rt::v1::Argument/*S*/],>/*E*/
	SLICE_PTR var3;	// &'static [&'static str]
	SLICE_PTR var4;	// &'static [::"core-0_0_0"::fmt::ArgumentV1<'static,>/*S*/]
	var3 = make_sliceptr(&ZRG2cD3binB_09FRAGMENTS0g.val, 0x1ull);	// _3 = MakeDst(&::"bin#"::#0::FRAGMENTS, 0x1 usize)
	var4 = make_sliceptr(&ZRG1cD3binF6const00g.val, 0x0ull);	// _4 = MakeDst(&::"bin#"::const#0, 0x0 usize)
	memset(&var2, 0, sizeof(struct e_ZRG2cE9core0_0_06option6Option1gBsSG4c_A3fmt2rt2v18Argument0g ));	// _2 = Variant(::"core-0_0_0"::option::Option<&'static [::"core-0_0_0"::fmt::rt::v1::Argument/*S*/],> #0, {})
	var1._0 = var3;
	var1._1 = var2;
	var1._2 = var4;	// _1 = Struct(::"core-0_0_0"::fmt::Arguments<'static,>, {_3, _2, _4})
	ZRG3cD8std0_0_02io5stdio7__print0g( var1 );
	// ^ Call( _0 = ::"std-0_0_0"::io::stdio::_print<'static,>( _1, ), bb1, bb2)
	/* ZST assign */
	return ;
	// ^ Return
bb2: _Unwind_Resume(); // Diverge
}
// ::"std-0_0_0"::rt::lang_start<(),>
static intptr_t  ZRG2cD8std0_0_02rt10lang_start1gT0(
		t_ZRTF0T0 arg0, // extern "Rust" fn() -> ()
		intptr_t arg1, // isize
		uint8_t **arg2 // *const *const u8
		) // -> isize

{
	intptr_t rv;
	struct s_ZRG2cD8std0_0_02rtH19closurelang_start_01gT0 var0;	// ::"std-0_0_0"::rt::closure#lang_start_0<(),>/*S*/
	struct s_ZRG2cD8std0_0_02rtH19closurelang_start_01gT0 *var1;	// &'#local0 ::"std-0_0_0"::rt::closure#lang_start_0<(),>/*S*/
	TRAITOBJ_PTR var2;	// &'#local0 dyn (for ::"core-0_0_0"::ops::function::Fn<(),Output{::"core-0_0_0"::ops::function::FnOnce<(),>}=i32,>+::"core-0_0_0"::marker::Sync+::"std-0_0_0"::panic::RefUnwindSafe)
	var0._0 = arg0;	// _0 = Struct(::"std-0_0_0"::rt::closure#lang_start_0<(),>, {a0})
	var1 = & var0;	// _1 = Borrow(Shared, _0)
	var2 = make_traitobjptr(var1, &ZRQG2cD8std0_0_02rtH19closurelang_start_01gT03cE9core0_0_03ops8function2Fn1gT0G6vtable0g.val);	// _2 = MakeDst(_1, &<::"std-0_0_0"::rt::closure#lang_start_0<(),>/*S*/ as ::"core-0_0_0"::ops::function::Fn<(),>>::vtable#)
	rv = ZRG2cD8std0_0_02rt19lang_start_internal0g( var2, arg1, arg2 );
	// ^ Call( retval = ::"std-0_0_0"::rt::lang_start_internal<'#local0,>( _2, a1, a2, ), bb1, bb2)
	return rv;
	// ^ Return
bb2: _Unwind_Resume(); // Diverge
}
// <::"std-0_0_0"::rt::closure#lang_start_0<(),>/*S*/ /*- */>::#drop_glue
static void  ZRIG2cD8std0_0_02rtH19closurelang_start_01gT0A9drop_glue0g(
		struct s_ZRG2cD8std0_0_02rtH19closurelang_start_01gT0 *arg0 // &'#omitted move ::"std-0_0_0"::rt::closure#lang_start_0<(),>/*S*/
		) // -> ()

{
	tUNIT rv;
	/* ZST assign */
	return ;
	// ^ Return
}
// <::"std-0_0_0"::rt::closure#lang_start_0<(),>/*S*/ as ::"core-0_0_0"::ops::function::Fn<(),>>::call<'#omitted,>
static int32_t  ZRQG2cD8std0_0_02rtH19closurelang_start_01gT03cE9core0_0_03ops8function2Fn1gT04call0g(
		struct s_ZRG2cD8std0_0_02rtH19closurelang_start_01gT0 *arg0, // &'#omitted ::"std-0_0_0"::rt::closure#lang_start_0<(),>/*S*/
		tUNIT arg1 // ()
		) // -> i32

{
	int32_t rv;
	t_ZRTF0T0 var0;	// extern "Rust" fn() -> ()
	var0 = arg0->_0;	// _0 = Use(a0*.0)
	(var0)( );
	// ^ Call( _1 = (_0)( ), bb1, bb2)
	rv = 0;	// retval = Constant(+0 i32)
	return rv;
	// ^ Return
bb2: _Unwind_Resume(); // Diverge
}
// <::"std-0_0_0"::rt::closure#lang_start_0<(),>/*S*/ as ::"core-0_0_0"::ops::function::FnMut<(),>>::call_mut<'#omitted,>
static int32_t  ZRQG2cD8std0_0_02rtH19closurelang_start_01gT03cE9core0_0_03ops8function5FnMut1gT08call_mut0g(
		struct s_ZRG2cD8std0_0_02rtH19closurelang_start_01gT0 *arg0, // &'#omitted mut ::"std-0_0_0"::rt::closure#lang_start_0<(),>/*S*/
		tUNIT arg1 // ()
		) // -> i32

{
	int32_t rv;
	t_ZRTF0T0 var0;	// extern "Rust" fn() -> ()
	var0 = arg0->_0;	// _0 = Use(a0*.0)
	(var0)( );
	// ^ Call( _1 = (_0)( ), bb1, bb2)
	rv = 0;	// retval = Constant(+0 i32)
	// ^ drop(a0)
	return rv;
	// ^ Return
bb2: _Unwind_Resume(); // Diverge
}
int main(int argc, const char* argv[]) {
	return ZRG2cD8std0_0_02rt10lang_start1gT0(ZRG1cD3bin4main0g, argc, (uint8_t**)argv);
}
__thread jmp_buf* mrustc_panic_target;
__thread void* mrustc_panic_value;
int8_t* __rust_alloc(uintptr_t a0, uintptr_t a1) {
	extern int8_t* __rdl_alloc(uintptr_t a0, uintptr_t a1);
	return __rdl_alloc(a0, a1);
}
void __rust_dealloc(int8_t* a0, uintptr_t a1, uintptr_t a2) {
	extern void __rdl_dealloc(int8_t* a0, uintptr_t a1, uintptr_t a2);
	__rdl_dealloc(a0, a1, a2);
}
int8_t* __rust_realloc(int8_t* a0, uintptr_t a1, uintptr_t a2, uintptr_t a3) {
	extern int8_t* __rdl_realloc(int8_t* a0, uintptr_t a1, uintptr_t a2, uintptr_t a3);
	return __rdl_realloc(a0, a1, a2, a3);
}
int8_t* __rust_alloc_zeroed(uintptr_t a0, uintptr_t a1) {
	extern int8_t* __rdl_alloc_zeroed(uintptr_t a0, uintptr_t a1);
	return __rdl_alloc_zeroed(a0, a1);
}
struct s_ZRG2c4core5alloc6Layout0g_A { uintptr_t a, b; };
void oom_impl(struct s_ZRG2c4core5alloc6Layout0g_A l) { extern void ZRG2cD8std0_0_05alloc8rust_oom0g(struct s_ZRG2c4core5alloc6Layout0g_A l); ZRG2cD8std0_0_05alloc8rust_oom0g(l); }
uint32_t panic_impl(uintptr_t payload) {extern uint32_t ZRG2cD8std0_0_09panicking16rust_begin_panic0g(uintptr_t payload);return ZRG2cD8std0_0_09panicking16rust_begin_panic0g(payload);}
