;
; File generated by cc65 v 2.18 - Git 67d7fb6
;
	.fopt		compiler,"cc65 v 2.18 - Git 67d7fb6"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_cprintf
	.export		_main

.segment	"RODATA"

L000008:
	.byte	$48,$45,$4C,$4C,$4F,$00

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	lda     #<(L000008)
	ldx     #>(L000008)
	jsr     pushax
	ldy     #$02
	jsr     _cprintf
	jmp     L00000A
L00000A:
	jmp     L00000A
	ldx     #$00
	lda     #$00
	jmp     L000006
L000006:
	rts

.endproc

