.PHONY: output/main.nes
output/welcome.nes:
	CC=../mrustc-master/cl65-wrapper ../mrustc-master/bin/minicargo --target ./target.toml --output-dir output ./welcome
	cp output/welcome output/welcome.nes

